bus1/dbus-broker

src/peer.c

label already is the target pointer. Otherwise there will be a segfault

fix peer_get_peersec

---

src/driver.c

should be a comparison, not an affectation

driver: fix typo

---

src/test-reply.c

Should be deinit, not init when releasing everything

test-reply: deinit the reply registry

---

src/launch/main.c

At least the first one in launch is relevant as we're using autocleanup for a maybe-unitialized variable (in the case when we return in the first error path)

Silence compiler warnings

---

meson.build
meson_options.txt
src/meson.build

This allows selinux support to be disabled even when libselinux is
installed.
Ref: https://wiki.gentoo.org/wiki/Project:Quality_Assurance/Automagic_dependencies

Add meson build option for selinux

---

src/broker/controller-dbus.c
src/broker/controller.c
src/broker/controller.h
src/bus/peer.c
src/bus/policy.c
src/bus/policy.h
src/util/selinux-fallback.c
src/util/selinux.c
src/util/selinux.h

The SID API is deprecated upstream, instead move to the
selinux_check_access() API which does the lookup from context to SID
internally. If this proves to have a significant overhead we should
work with upstream SELinux to come up with a non-deprecated solution.
Addresses issue #16.

util/selinux: move from using security IDs to using security contexts

---

meson.build
src/launch/main.c

Rather than hard-coding /usr/bin/, lets use $bindir. You can still
override it via --broker=, but the default should now be sufficient.

launch: use $bindir to spawn dbus-broker

---

src/broker/controller-dbus.c
src/broker/controller.c
src/broker/controller.h
src/bus/activation.c
src/bus/activation.h
src/bus/driver.c
src/bus/driver.h
src/launch/main.c

This can happen if the unit in question has been masked (or if it does not exist, but that would be a configuration failure). In this case, the requesting client should not hang forever, but rather receive a proper error reply.
This addresses issue #28.

Properly fail activation requests if systemd cannot activate them

---

src/broker/broker.c
src/broker/broker.h
src/broker/main.c
src/launch/main.c
src/meson.build
src/util/log.c
src/util/log.h

This adds the discussed log infrastructure, allowing us to push messages to systemd-journal or stderr, depending on which one is configured.
See the first patch for details on the infrastructure itself. The other patches just add the integration to dbus-broker and dbus-broker-launch. The idea there is to open the log FD in the launcher and pass it to dbus-broker just like the controller FD. By default, logging is disabled, so our test infrastructure still works as expected.
So far, we only initialize the log-context on `struct Broker`, but no messages are printed. This needs to be done as a follow-up.

Log Infrastructure

---

src/broker/broker.c
src/bus/bus.c
src/bus/bus.h
src/bus/driver.c
src/bus/peer.c
src/dbus/message.c
src/dbus/message.h

We should log if any message deliver fails unexpectedly. For now, add the logging for policy failures, which is most likely the most fragile and hard to debug. In the future we will add more metadata to the logging and extend it to log in more cases.

Add basic logging infrastructure

---

src/bus/match.c
src/bus/test-match.c

The {path,arg0}_namespace= keys filter for any path/arg0 that is equal
that they, or a descendent of their namespace. Right now, we
incorrectly match for ancestors.
While at it, extend the test cases and document failures we need to
look into.

Fix inverted {path,arg0}_namespace= match-logic

---

src/dbus/test-message.c

The headers were fixed to be LE, but the fields were set using native endianness.

message/test: fix on BE architectures

---

units/system/dbus-broker.service.in
units/user/dbus-broker.service.in

At start-up this makes no (or very little) difference, but at shutdown
this ensures that basic.target is shutdown before dbus-broker.service
is. In particular, we want clients to have the chance to shutdown
gracefully without having IPC pulled out from under them.

units: order dbus-broker.service before basic.target

---

meson.build

Some distributions don't rename the scripts to remote the .py extension

build: fallback to rst2man.py

---

src/launch/main.c

Until today, we used a rather random backlog limit for AF_UNIX listener
sockets. However, it turns out the limit is used as literal limit on
linux to control the maximum number of pending connection attempts.
Since there is no fair queue sharing involved, all connecting users
share this single queue. Malicious peers can easily exhaust this limit
and cause connection failures for other peers.
Unfortunately, there is no known way to avoid this with AF_UNIX.
However, we can, at least, avoid the random magic number and stick to
the upstream limit. As it turns out, this is also what most other
AF_UNIX users do.
Additionally, document this situation. Fortunately, this will no longer
be an issue with bus1, since it employs fair queue sharing.

launch: increase listener backlog to SOMAXCONN

---

meson.build
src/bus/policy.c
src/bus/policy.h
src/launch/policy.c
src/launch/policy.h

Allow pseudo-compatibility with at_console= policies, by considering all system users at_console=false and all regular users at_console=true. This is done by allowing the UID specified in the broker API to be an upper/lower bound in addition to an exact match.

uid ranges

---

src/broker/broker.c
src/broker/broker.h
src/broker/controller-dbus.c
src/broker/controller.c
src/broker/controller.h
src/bus/activation.c
src/bus/driver.c
src/bus/driver.h
src/bus/listener.c
src/bus/listener.h
src/bus/peer.c
src/bus/peer.h
src/launch/main.c
test/dbus/test-driver.c
test/dbus/util-broker.c

The broker allows names to be added/removed and the policy to be set for an existing listener. Together, this allows replacing all the configuration at run-time.
The launcher reloads the configuration, then removes all names that are no longer present, sets the new policy on the listener (which in turn updates the policy of each of the peers spawned from the listener). This can either be triggered by raising SIGHUP in the launcher, or by calling the internal ReloadConfig() call from the broker.
The broker now exposes the standard ReloadConfig() call on the org.freedesktop.DBus API which is forwarded to the launcher.

Add SetPolicy() call to the controller

---

units/system/dbus-broker.service.in
units/user/dbus-broker.service.in

Use busctl to call ReloadConfig() on dbus-broker.
$ systemctl --user reload dbus
can now be used to reload the dbus configuration in a blocking way.

units: hook up ExecReload

---

units/user/dbus-broker.service.in

Currently `systemctl --user reload dbus` would reload the system instance

units: fix reloading for user instance

---

src/broker/controller.c
src/bus/activation.c
src/bus/match.c
src/bus/name.c
src/bus/peer.c
src/bus/policy.c
src/bus/reply.c
src/dbus/socket.c
src/launch/config.c
src/launch/main.c
src/launch/policy.c
src/util/dispatch.c
src/util/user.c

This renames c_{rbnode,list}_unlink_init() by dropping the _init()
suffix. Update all the callers to call the new function. This is not
a functional change.
Only one instance existed that already called the function without the
_init() suffix, this is left unchanged, which means that it will
reinstantiate the node after unlinking it, which it did not used to do.
However, the old behavior was likely not intentional.

subprojects: update

---

src/launch/config.c
src/launch/config.h
src/launch/main.c
src/launch/nss-cache.c
src/launch/nss-cache.h
src/launch/test-config.c
src/meson.build

The main feature of this PR is to use the correct UID when spawning transient units via systemd.
A few more nss fixes: we now cache the lookups, so we only resolve a user/group once during config/policy parsing. We immediately drop the cache though, so everything is re-resolved on reload.
We also now support user/group being the UID/GID directly, like the reference implementation always did. Lastly, we follow systemd and hard-code the "root" user/group to resolve to UID/GID 0 without going through NSS.

launcher: rework nss handling

---

src/bus/policy.c
src/dbus/message.c
src/launch/policy.c
src/launch/policy.h
test/dbus/util-broker.c

Improve warnings emitted by the launcher on deprecated policy. Make sure we always log when ignoring policy that is not a noop, but do not log about ignoring policy that would not have any effect.
This also fixes an (obscure) bug related to eavesdrop policies.

launch/policy: improve warnings

---

meson.build
src/launch/main.c

This integrates the existing '-Dsystem-console-users=' option with dbus-broker-launch, so the data is actually used.

launch: resolve system-console-users

---

src/bus/match.c

Use the new *_continue() style list iterators to avoid hard-coding list
internals in the match code.
Related submodule update was already pushed to master.

bus/match: use *_continue() iterators

---

src/launch/main.c

Now that we explicitly support several launcher instances per scope
(i.e., systemd instance), we need to further namespace the service
names we generate ourselves.
Each launcher instance has a unique name on the bus corresponding
to the scope, and systemd binds the transient unit to this name.
The new naming scheme becomes:
`dbus-<launcher unique name>-<service name>@<instance number>.service`

launch/transient: namespace transient units by launcher instance

---

meson.build
meson_options.txt

Make building documentation opt-in.
See: <http://lists.openembedded.org/pipermail/openembedded-devel/2018-March/117419.html>.

build: make documentation optional

---

src/launch/main.c
src/launch/nss-cache.c
src/launch/nss-cache.h

NSS is prone to deadlocks with dbus. Read /etc/{passwd,group} directly where possible, and only fall back to NSS if we have to.
When we fall back to NSS, log before/after each call to make deadlocks easier to debug.

Avoid NSS lookups

---

docs/dbus-broker-launch.rst
docs/dbus-broker.rst
src/broker/broker.c
src/broker/main.c
src/broker/main.h
src/launch/main.c
src/units/system/dbus-broker.service.in
src/units/user/dbus-broker.service.in
test/dbus/util-broker.c

This was never really used, so just hardcode the current behaviour, we can reintroduce the switch if it ever becomes relevant.

Drop the --verbose switch

---

src/broker/broker.c
src/broker/broker.h
src/broker/main.c
src/bus/bus.c
src/bus/bus.h
src/bus/driver.c
src/launch/main.c
test/dbus/test-driver.c
test/dbus/util-broker.c

This is required by the spec. Also, allow method calls with an empty destination.

driver: add Peer interface

---

src/bus/driver.c
src/bus/match.c
src/bus/match.h
src/bus/peer.c
src/bus/test-match.c

This should all but eliminate false-positives when iterating potential matches for a signal.
In a follow-up, we will ref-count identical matches, to further reduce the number of matches we have to linearly iterate through.

match: index by path/interface/member in addition to destination

---

docs/dbus-broker.rst
src/broker/controller-dbus.c
src/launch/main.c
test/dbus/util-broker.c

We never use the term "Launcher" to describe technical parts of dbus-broker. We always call it "Controller". Make sure the D-Bus interface uses the same terms.

broker: org.bus1.DBus.Launcher -> org.bus1.DBus.Controller

---

src/launch/config.c
src/launch/config.h
src/launch/main.c
src/launch/nss-cache.c
src/launch/nss-cache.h
src/launch/test-nss-cache.c
src/meson.build

Hey
This is in preparation for the `<user>%</user>` attribute of the XML config. This does not fully implement it, but only contains the preparations in the NSS cache.
The only undiscussed change here is the re-introduction of the 'root' group as pre-populated entry. Given that we have to pre-propulate the full "struct passwd" now, this means that we must also know the "pw->pw_gid" entry. Lets just define this as 0 and reintroduce the 'root' group as group 0. This is universally true and should be fine.
Thanks
David

Extend NSS Cache

---

meson.build
src/launch/main.c
src/meson.build
src/util/audit-fallback.c
src/util/audit.c
src/util/audit.h

Make sure to drop privileges before executing dbus-broker. Look at the
<user> XML attribute and apply the uid/gid if set.

launch: drop privileges before startup

---

.cherryci/ci-test

Now that the CI environment contains the required dependencies, lets
try and enable selinux+audit.

build: enable selinux+audit in CI

---

src/launch/main.c

Hook into the reload notification as systemd expects. This appears to be purely
informational, but seems worth following the recommendations nonetheless.

launcher: notify systemd about reloading

---

src/launch/main.c

This is a follow-up to 5d90e2d571b40ad6a8e9894f3bb38fe22d50fd06.

launcher/start-service: use job-mode 'replace' also for transient units

---

src/bus/match.c

The calls to flush() walks the tree, essentially unlinking each element
and rebalancing the tree. We need to use the _safe() loop iterator rather
than the _safe_postorder() one for this to be valid, as documented in
c-rbtree.h.

match: fix iteration order of flush()

---

src/bus/driver.c
src/bus/match.c
src/bus/match.h
src/bus/peer.c
src/bus/peer.h

This only affects the case when the message transaction fails due to resource exhaustion. It used to be that if the receiver had a matching match installed they would be disconnected (treated as a solicited message). However, this semantics is not standardised, and installing matches for directed matches is not common practice.
Simplify the semantics by treating a directed signal just like a method call with the REPLY_NOT_EXPECTED flag set. This means that if the message could not be delivered it is dropped. This essentially implies that directed signals are recommended against if you want your client to be robust.

Treat directed signals like method calls without replies

---

src/bus/bus.c
src/bus/bus.h
src/bus/driver.c
src/bus/match.c
src/bus/match.h
src/bus/peer.h
src/bus/test-match.c

This simplifies the code, and keeps anything not match-related (policy decisions) in the caller. It marginally improves the worst case performance, but to avoid the O(n) worst-case performance, we would need to introduce Bloom filters, so optimizing this further does not seem worth the effort.

match/iterator: replace iterators with getters for destinations

---

src/bus/bus.c
src/bus/bus.h
src/bus/driver.c
src/bus/peer.c
src/util/test-user.c
src/util/user.c
src/util/user.h

Make sure we log about all quota failures. Also, log about failing transactions due to quota failure (separately). Together this should make debugging considerably simpler.
There are still cases where clients are disconnected which are not logged, namely where the peer has exceeded its own quota or attempts a protocol violation. These should be addressed separately, as they are more complicated to get right, and less likely to crop up in real life.
Calling org.freedesktop.DBus.GetId on org.freedesktop.DBus in a loop without reading the replies now logs about the resulting disconnect as follows:
```
UID 1000 exceeded its 'bytes' quota on UID 1000.
Peer :1.107 is being disconnected as it does not have the resources to receive a reply or unicast signal it expects.
```

log: add log messages on quota failures and related disconnects

---

src/bus/driver.c
src/bus/peer.c
src/bus/policy.c
src/bus/policy.h
src/dbus/message.c
src/launch/config.c
src/launch/config.h
src/launch/policy.c
src/launch/policy.h
src/util/common.h
test/dbus/util-broker.c

Internally, the implementation is symmetric, allowing recv_broadcast to
be supported too. However, that is not supported by the policy language,
nor the parser.
Also, extend the message logging to include the number of file descriptors,
as that can now influence policy decisions.

policy: implement send_broadcast, min_fds and max_fds parameters

---

src/broker/controller-dbus.c
src/broker/controller.c
src/broker/controller.h
src/bus/driver.c
src/bus/driver.h
src/launch/config.c
src/launch/main.c

Make sure we don't trigger a hard failure, but refuse to load invalid config. We may want to audit the config parser and consider more cases invalid rather than silently ignored, but that would be a follow-up.
```
Jun 27 17:32:44 teg-x270 systemd[1]: Reloading D-Bus System Message Bus.
Jun 27 17:32:44 teg-x270 dbus-broker-launch[763]: Invalid XML in /usr/share/dbus-1/system.conf +141: mismatched tag
Jun 27 17:32:44 teg-x270 busctl[1729]: Config invalid. Reload ignored.
Jun 27 17:32:44 teg-x270 systemd[1]: dbus-broker.service: Control process exited, code=exited status=1
Jun 27 17:33:57 teg-x270 dbus-broker-launch[763]: Caught SIGHUP
Jun 27 17:33:57 teg-x270 dbus-broker-launch[763]: Invalid XML in /usr/share/dbus-1/system.conf +141: mismatched tag
Jun 27 17:33:57 teg-x270 …
```

Gracefully handle ReloadConfig and SIGHUP when the config is invalid

---

src/launch/main.c

musl doesnt implement secure version
Signed-off-by: Khem Raj <raj.khem@gmail.com>

use getenv on non-glibc systems

---

src/bus/policy.c
src/launch/main.c
src/launch/policy.c
src/launch/policy.h
src/meson.build
src/util/apparmor.c
src/util/apparmor.h
src/util/test-apparmor.c
test/dbus/util-broker.c

The intention with this patch is to make it simple to carry a downstream patch in case a distribution wants AppArmor support and carries the required downstream kernel patches too.
So far only the `mode="required"` has been tested to verify that it correctly shuts down the broker on config reload and then refuses to restart.

apparmor: add skeleton support

---

src/broker/broker.c
src/util/proc.c
src/util/proc.h
test/dbus/test-driver.c

This makes the broker use the parent seclabel for the driver, as discussed offchannel. The reasoning is in the commit-message / inline-comment.

broker: use parent seclabel for the driver

---

src/util/audit-fallback.c
src/util/audit.c

This makes the audit code more robust and fixes a bug. Firstly, gracefully handle the case when we are started without CAP_AUDIT_WRITE, and consider this the same as not having audit support (fallback to stderr). Secondly, make sure the broker correctly inherits CAP_AUDIT_WRITE from its parent, when possible and enabled.
Also make the error-handling a bit more robust after reviewing libcap-ng (whose documentation leaves much to be desired).

audit fixes

---

src/launch/config.c
src/launch/nss-cache.c
src/launch/policy.c

It turns out to be more common than we'd like to have usernames in dbus config that are not defined on the system. Improve the logging and caching of these invalid entries.

Better handle invalid usernames in the config parser

---

.gitmodules
README
meson.build
src/launch/main.c
src/meson.build

c-ini is a stand-alone library, compatible with glib's g_key_file. Use
it to parse the DBus service files, dropping the glib dependency.

launcher: use c-init rather than g_key_file

---

src/units/system/dbus-broker.service.in

This is mostly for the sake of documentation and catching bugs early.
dbus-broker does not need write-access to any filesystem nor does it
need access to devices or the network stack.

units/system: run in namespaces

---

src/bus/peer.c
src/dbus/connection.c
src/dbus/connection.h

Rather than silently disconnecting, report either SASL failures or
protocol violations to the caller so they can decide what to do.
In the caller, log and disconnect.

connection: expose SASL issues

---

src/launch/main.c

The reference implementation ignores all error-codes from
bus1_desktop_file_load(), so we should do the same. However, none of
these errors is expected, so lets make sure we print a warning.
For reference, see: https://bugzilla.redhat.com/show_bug.cgi?id=1665450

launch: align errors when reading service-files with dbus-daemon(1)

---

src/meson.build
src/util/misc.c
src/util/test-misc.c

Fix the `umul64_saturating` helper. See commit+commitmsg for details.

util/misc: fix saturating multipliers

---

src/launch/launcher.c
src/launch/service.c
src/launch/service.h

The 'state' field is currently used for 2 purposes: To track whether a
service was pushed into the broker, and to track whether a service was
found during reload. While both can be tracked in the same state, it
makes things overly complex and the current solution is definitely
wrong. We do not consider failing configuration-reloads, which happen
to leave the reload-tag untouched. In those cases, we trigger the wrong
assertion in the activation path.
This patch splits the state into separate booleans. One to track
whether or not a services was pushed into the broker ('running'),
and one as throw-away tag for reload tracking ('reload_tag'). Note that
the value of the reload-tag is only correct *DURING RELOADS*. It is
garbage at all other times. Do not verify it. It is solely meant to be …

launch/service: fix state tracking

---

src/bus/activation.c
src/bus/activation.h
src/bus/driver.c
src/bus/match.c
src/bus/match.h
src/bus/name.c
src/bus/name.h
src/bus/reply.c
src/bus/reply.h
src/dbus/connection.c
src/dbus/connection.h
src/dbus/socket.c
src/dbus/socket.h
src/meson.build
src/util/user.c
src/util/user.h
test/dbus/test-driver.c

This implements the fdo.DBus.Debug.Stats interface, in particular it implements GetStats() which allows to query all the accounting information of a running dbus-broker instance.
This will hopefully allow us to further debug any accounting issues people report to us.

Implement org.freedesktop.DBus.Debug.Stats.GetStats()

---

src/launch/launcher.c
src/launch/service.c
test/dbus/test-driver.c

If SystemdService and Exec are both missing from the service files
then we still treat the name as activatable, but no explicit action
is needed from us in order to start it (it is going to be started
by the system, and activation is only used to avoid a race).
See discussion here: https://github.com/systemd/systemd/pull/14405

launch/service: support noop activation files

---

src/launch/policy.c

dbus-broker crashes on startup if the policy includes ```<selinux>``` elements. I have verified on a yocto-based distro that with the following fixes everything works. A process with the correct label is allowed to own an interface, and a process without the correct label is not.
Fixes #212

Fix running dbus-broker with <selinux> in the policy

---

src/bus/driver.c
src/bus/match.c
src/bus/match.h
src/bus/peer.c
src/bus/test-match.c

As it turns out `dbus-monitor` unconditionally prepends `eavesdrop=true`
to all filters it installs. This was necessary back in the days when it
actually used eavesdropping, but with BecomeMonitor() this is no longer
necessary. However, the code is still there and used in the wild.
To support `dbus-monitor` with custom matches, this commit makes
BecomeMonitor() treat the matches special and allows parsing `eavesdrop`
rules just like we used to:
commit ce67e4e7091416d8cd7021b63babbfed7a01d7fd
Author: Tom Gundersen <teg@jklm.no>
Date:   Thu Aug 3 08:40:52 2017 +0200
match: drop support for eavesdropping
We still silently ignore the flag, since it carries no meaning for
monitors, and in all other cases we do not allow it, anyway.

bus/driver: allow eavesdrop filters for monitors

---

meson.build
meson_options.txt
src/broker/broker.c

This introduces a new meson-option called 'linux-4-17=false', which when set to `true` allows us to depend on linux v4.17 features. In particular, this allows us to enforce `SO_PEERSEC` to read our own credentials, rather than reading `/proc/<ppid>`.
The idea here is to have this as a smooth transition and allow people to use the new features in controlled environments. At some point, we will set the option to default to `true` and reject builds with this set to `false`. This way, we have a backwards compatible option and will not break build-setups that do not care for this.

broker: force SO_PEERSEC if new option linux-4-17 is set

---

src/broker/broker.c

When querying for LSM credentials of our parent, we want the strategy
forward to be using SO_PEERSEC. In the fallback-path, we use /proc on
the parent pid. To reduce the differences between those paths, actually
use the pid from the controller-socket over getppid(). This now reduces
the differences to just where we fetch the data from.

broker/broker: use SO_PEERCRED.pid over getppid()

---

src/launch/main.c

We incorrectly forward launcher errors from the launcher namespace to
the main application namespace. This is wrong, these are separate
namespaces, so we have to fold the error.
This fixes an issue were we would treat LAUNCHER_E_INVALID_CONFIG as
MAIN_EXIT, and thus not return with an error code.
This should fix #216.

launch/main: fix error propagation

---

src/broker/broker.c
src/bus/bus.c
src/bus/bus.h
src/bus/driver.c
src/util/sockopt.c
src/util/sockopt.h
test/dbus/test-driver.c

Since dbus-specification-0.53 the GetConnectionCredentials() call now returns the list of supplementary groups as `UnixGroupIDs`. This series implements this, including a handful of minor fixes.

Implement UnixGroupIDs in GetConnectionCredentials()

---

src/launch/service.c
src/meson.build
src/util/systemd.c
src/util/systemd.h
src/util/test-systemd.c

This series imports a new helper similar to `systemd-escape(5)`, which allows us to escape systemd unit names. It then uses it to correctly escape the unit-name suffix for transient units.
This attempts to fix #230.

launcher: escape transient unit names

---

src/broker/main.c
src/launch/launcher.c

A set of 3 error-path fixes. The first two fix `dbus-broker` from using
the default exit-path for audit/selinux initialization failures, and
thus properly printing debug messages.
The third fix changes `sd_event_loop()` to fold the return code. It uses
a separate error-domain, so we should always properly fold and
participaite in the error-trace.

broker: fix some error-paths to be more verbose

---

src/launch/config.c

If we cannot open a configuration file, be more verbose about it. We
already log a lot about errors in configuration files, so this just adds
one more, which can hopefully help in diagnosing such errors more
easily.

launch/config: be more verbose about missing files

---

src/util/audit-fallback.c
src/util/audit.c
src/util/audit.h
src/util/selinux.c

The SELinux log callback includes a message type.  Not all messages are
auditable and those that are don't have the different audit types.  Update
the auditing accordingly.
If the message is not auditable, write it to stderr.
Signed-off-by: Chris PeBenito <chpebeni@linux.microsoft.com>

util/selinux: Change auditing based on the log type.

---

src/util/audit.c
src/util/audit.h
src/util/selinux.c

After [discussions on the SELinux mail list](https://lore.kernel.org/selinux/CAEjxPJ6=s504ZdWevGALxxksCF4tsQ46meD8iCg7sCFoV9sKSA@mail.gmail.com/) related to the content of audit
messages that libselinux generates, it was determined that no
SELINUX_ERROR messages are auditable after all.  In the future, if there
are ones that need to be audited, they will have a different value in the
libselinux log callback and this can be restored.
Audit messages added in bus1/dbus-broker#240 are still appropriate.
Signed-off-by: Chris PeBenito <chpebeni@linux.microsoft.com>

util/audit: Revert UTIL_AUDIT_TYPE_SELINUX_ERROR audit type.

---

src/bus/driver.c
src/launch/service.c
src/launch/service.h

Track the `ActiveState` property of systemd units associated with dbus
services. This allows us to better track when a service activation fails
beyond just the `StartUnit()` call.
Until now we only ever tracked failure of the `StartUnit()` call itself.
However, this call does not wait for a service to be fully activated,
but merely waits for the start-job to be queued in systemd. This means,
we only see failures of the unit-verification and transaction checks,
but never get any results of the transaction itself.
In particular, this means that if any unit successfully spawns, but then
fails before claiming a bus-name, we never see this failure, because it
is reported only late by systemd.
This commit extends the launcher to track all systemd units we activate
for as long as a dbus-service …

launch/service: track systemd unit state

---

src/launch/service.c

When launching transient units, we want failed units to be garbage
collected immediately. All relevant information is retained in the logs
and further activations of the same unit will increment an instance
counter, and thus use a different unit name.
CC: @benzea #209

launch/service: use CollectMode=inactive-or-failed

---

src/launch/config.c

Print the configuration path whenever we hit EPERM or EACCES. This makes it easier to debug mis-configured systems.

launch/config: be more verbose about denied configuration access

---

docs/dbus-broker.rst
src/broker/controller-dbus.c
src/broker/controller.c
src/broker/controller.h
src/bus/activation.c
src/bus/activation.h
src/bus/bus.h
src/bus/driver.c
src/bus/driver.h
src/launch/launcher.c
src/launch/service.c
src/launch/service.h

Extend the activation communication between broker and launcher to use
serial numbers. This allows us to discard stale activation failures and
closes a race condition where we would incorrectly fail new activations
immediately after a previous service exited.
@lucab @cgwalters

broker: pass serial numbers with activations

---

meson.build
src/util/audit.c
src/util/audit.h
src/util/selinux.c

I picked up the patch from @pebenito so we don't forget about it. The original PR was #240 and was closed automatically when we switched the main branch.
I also updated the `meson.build` dependency to the now released `audit-3.0`. Once that hits the bigger distro channels, I think we can merge this. I would like to wait for the `libselinux` release as well, but this seems like something we can carry with an `#ifndef` until they prep a new release.
Anyway, leaving this here so we don't forget about this.

[PENDING] util/selinux: Add additional audit message types.

---

src/units/system/dbus-broker.service.in

It is causing significant delays during boot, see
https://bugzilla.redhat.com/show_bug.cgi?id=1976653.
Also, the justification for this ordering was a misunderstanding:
> Secondly, make sure to order after sysinit.target, so basic system
> setup is done before we start. This is especially important to make
> sure the launcher can resolve user names and read the disk.
Ordering after sysinit.target is not necessary to "read the disk". The
basic file system is established before services are started.  Some
other file systems may be mounted later, but system services should
not access those file systems. (In cases where they do,
RequiresMountsFor= may be used, but dbus-broker shouldn't require any
special paths, afaik). OTOH, sysinit.target is not enough to establish
lookup of arbitrary user …

units: drop the ordering after sysinit.target

---

src/units/user/dbus-broker.service.in

Run user service in session.slice
The dbus-broker service should run in the session slice when running as
a user service.
From [DESKTOP_ENVIRONMENTS][1]:
> The purpose of this grouping is to assign different priorities to the
> applications. This could e.g. mean reserving memory to session
> processes, preferentially killing background tasks in out-of-memory
> situations or assigning different memory/CPU/IO priorities to ensure
> that the session runs smoothly under load.
And from man:systemd.special(7):
> session.slice
>  All essential services and applications required for the session
>  should use this slice. These are services that either cannot be
>  restarted easily or where latency issues may affect the interactivity
>  of the system and applications. This includes the display …

Run user service in session.slice

---

test/dbus/test-fdstream.c

```
==365== FILE DESCRIPTORS: 6 open (3 std) at exit.
==365== Open AF_UNIX socket 7: <unknown>
==365==    at 0x4A4A8BB: socket (syscall-template.S:120)
==365==    by 0x40597C: util_broker_connect_fd (util-broker.c:558)
==365==    by 0x4033DC: test_fd_stream (test-fdstream.c:235)
==365==    by 0x403599: main (test-fdstream.c:284)
==365==
==365== Open AF_UNIX socket 6: <unknown>
==365==    at 0x4A4A8BB: socket (syscall-template.S:120)
==365==    by 0x40597C: util_broker_connect_fd (util-broker.c:558)
==365==    by 0x4033DC: test_fd_stream (test-fdstream.c:235)
==365==    by 0x403599: main (test-fdstream.c:284)
==365==
==365== Open AF_UNIX socket 5: <unknown>
==365==    at 0x4A4A8BB: socket (syscall-template.S:120)
==365==    by 0x40597C: util_broker_connect_fd (util-broker.c:558)
==365== …
```

tests: fix an fd leak

---

src/util/apparmor.c

This header does not seem to be required.
Tested with -Dapparmor=true and -Daudit=true/-Daudit=false.
Bug: https://bugs.gentoo.org/873082

Drop '#include <libaudit.h>' from src/util/apparmor.c

---

src/bus/driver.c
src/bus/driver.h

A set of 3 patches reworking how we currently return EPERM from stubs. The first two commits are fixed that should go in anyway, the third is a suggestion on how to improve the situation with stubbed driver calls.
Cc: @draconicfae @teg

bus/driver: rework EPERM handling

---

src/launch/service.c
src/launch/service.h

This series delays the service-start until we correctly installed all matches. With #285 we now wait for `LoadUnit()` to return before installing our D-Bus matches, so we know the proper service object-paths. However, this change caused a race-condition where the service might spawn and fail faster than we can process the reply to `LoadUnit()`. This is quite unlikely, given that the `LoadUnit()` operation is scheduled first. However, with the coalesced message-transmissions of dbus-broker, the different messages we schedule are often transmitted in a single syscall and thus on slower machines this race is actually possible to hit.
Regardless, this needs to be fixed, so we simply delay the start-unit operation until the matches are installed. This series starts with a bunch of cleanups and …

launch: delay service-start until matches are installed

---

src/launch/config.c
src/launch/config.h

A small series with 2 minor fixes to the libexpat handling, and finally a workaround to forward AT_RANDOM to libexpat, rather than making libexpat fetch its own entropy from the kernel.
Cc: @agners #319

launcher/config: use AT_RANDOM for libexpat hash seeds

---

src/util/selinux-fallback.c
src/util/selinux.c
src/util/selinux.h

Add support for selinux permissive mode. Since we use `selinux_check_access()` rather than the deprecated direct AVC queries (which dbus-daemon uses), we don't get the automatic enforcing-mode check of the AVC helpers. Instead, we have to manually query `security_getenforce()` to get the value.
This implementation is modeled similar to the implementation in systemd (src/core/selinux-access.c). It uses a similar optimization via the status-page to avoid an additional syscall on each policy check.
Reported in #315.

selinux: support permissive mode

---

src/launch/test-config.c
src/util/log.c
src/util/misc.c
src/util/misc.h
src/util/test-misc.c
src/util/test-proc.c

Provide proper abstractions for memfd operations. This is especially necessary with the new `MFD_EXEC` and `MFD_NOEXEC_SEAL` features of the kernel, which requires all memfd users to update the code to use one of the new flags.
Unfortunately, they decided against providing `MFD_NOEXEC`, but instead just provide `MFD_NOEXEC_SEAL`, which is a combination of `MFD_ALLOW_SEALING`, `MFD_NOEXEC`, and `F_SEAL_EXEC`. This is really awkward to use in helpers, but I think I got something that works well enough.
Reported in #322.

memfd: provide proper abstractions

---

src/launch/config.c
src/launch/launcher.c
src/meson.build
src/util/fs.c
src/util/fs.h
src/util/test-fs.c

This introduces `util/fs.c` with initial helpers to enumerate directories into a collection, and then sorting them based on lexicographic order. It then switches our two only users of `readdir()` over to use it, thus getting predictable directory enumeration behavior.

Enumerate directories in ordered fashion

---

.packit.yml

Build (and test) dbus-broker on all active Fedora releases using Packit.
This uses Fedora's spec file (from Rawhide) with a couple of tweaks, so
we don't have to ship our own.
Replaces: https://github.com/bus1/dbus-broker/pull/279

ci: introduce Packit

---

test/dbus/meson.build
test/dbus/util-broker.c

This gets rid of two meson deprecation warnings and also makes most (\*) of the reference tests work with newer dbus-daemon (F39 and Rawhide), that started using path-based sockets instead of abstract ones.
(\*) 
```
$ meson test -C build --suite 'dbus-daemon(1)' --print-errorlogs                                                                                                                            
ninja: Entering directory `/home/fsumsal/repos/dbus-broker/build'                                                                                                                           
[7/7] Linking target test/dbus/test-fdstream                                                                                                                                                
1/5 …
```

A couple of test tweaks

---

meson.build
meson_options.txt
src/meson.build
test/dbus/meson.build
test/dbus/util-broker.c

This PR introduces two changes: making the reference tests work without a build dir and, subsequently, allowing both reference and unit tests to be installed along with dbus-broker itself, so they can be later used to verify if the installed dbus-broker behaves as expected.
The first change unifies an already existing behavior, where the path to a dbus-daemon binary can be tweaked via an environment variable - the name of the variable was changed to `TEST_DBUS_DAEMON`, and a new env variable - `TEST_DBUS_BROKER` - was introduced that does the same thing, but for the dbus-broker binary (instead of hardcoding the path directly). Both paths now default to `/usr/bin/{dbus-daemon,dbus-broker}`; when running the tests using meson the path for dbus-broker is overridden to point to the just built …

test: allow installing built test executables

---

.packit.yml
packit.yml

(Replacement for #355 to retrigger packit due to configuration errors)

packit: extend the configuration and enable more runs

---

src/bus/driver.c
src/util/fdlist.c
src/util/fdlist.h
src/util/test-fdlist.c

Duplicate FDs for queued messages to ensure they stay around until a message is queued. This fixes a bug where we might try to send messages referencing closed file-descriptors.

bus/driver: duplicate FDs for queued messages

---

.github/workflows/codeql.yml
.github/workflows/meson-tests.yml
src/bus/match.c
src/bus/test-match.c
src/util/misc.c
src/util/misc.h
src/util/test-misc.c
test/dbus/test-matches.c

This is a rollup of #366 and #369, including minor adjustments on top.

Rollup of multiple PRs

---

src/dbus/socket.c

The socket layer assumes that computing `NULL + 0` produces `NULL`. Unfortunately, this is UB. Protect against this pointer arithmetic and ensure we correctly skip empty IOVs when consuming socket buffers.
Reported in #365.

dbus/socket: protect against no-op arithmetic on NULL pointers

---

src/launch/policy.c

2 fixes related to policy imports with invalid uids/gids.
Initial report was in #360.

launch/policy: fix misallocations and leaks with invalid uids/gids

---

src/launch/launcher.c

This is useful when an asset manager wants to install a system service while /usr/ is read-only (e.g.: local system services running on a different namespaced image)
spec and dbus-daemon corresponding change: https://gitlab.freedesktop.org/dbus/dbus/-/merge_requests/467

launcher: allow searching for system-services in /etc/ and /run/

---

.github/workflows/fuzz.yml

As v3 is deprecated and is going away at the end of January.
See: https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/

ci: bump actions/upload-artifact to v4

---

src/launch/nss-cache.c
src/util/string.h
src/util/systemd.c

Again some warnings of GCC that will break builds with `-Werror` but are false positives. See each one for details.

Silence new GCC warnings

---

.github/workflows/meson-tests.yml

Switch the base image again from Fedora to Arch Linux. This requires us to disable SELINUX in the unit-tests, but those will be run by the packit integration, so we should be fine.
The advantages are:
* Image builds take *significantly* less time: 10min for Fedora, 3min for Arch Linux (on the same infrastructure).
* Images are significantly smaller in size: 6GiB for Fedora, 3GiB for ArchLinux (with the same packages).
We also get rolling releases, allowing us to control at which point we can update. We do not expose the CI system to untrusted inputs, anyway (nor do we pass sensitive data to it).

ci: rebase on archlinux

---

src/launch/launcher.c
src/units/system/dbus-broker.service.in
src/units/user/dbus-broker.service.in

dbus-broker supports reload but the service type is `notify`. This PR updates the service type to `notify-reload`.

Add notify-reload support to dbus-broker

---

src/util/audit.c

Update util_audit_log to use audit_log_user_message for UTIL_AUDIT_TYPE_POLICYLOAD and UTIL_AUDIT_TYPE_MAC_STATUS, and audit_log_user_avc_message for UTIL_AUDIT_TYPE_AVC. The result parameter is now passed to audit_log_user_message, set to 1 by default.
This change ensures proper argument order for ausearch utility as discussed in linux-audit/audit-userspace#394.
Fixes #387

util/audit: Correct usage of audit logging functions

---

src/bus/bus.h
src/bus/driver.c
src/bus/match.c
src/bus/match.h
src/bus/name.c
src/bus/name.h
src/bus/peer.c
src/bus/peer.h
src/bus/test-match.c
src/bus/test-name.c
src/util/misc.c
src/util/misc.h
test/dbus/test-driver.c

Extend the name, bus, and peer registries to keep track of the number of active entries, as well as their peak values. This information is then exposed via `GetStats()`, as documented in the specification.
This contains a rebase of #393, making use of the new infrastructure.

bus/driver: add some standard stats to Debug.GetStats

---

src/broker/main.c
src/util/apparmor.c
src/util/audit-fallback.c
src/util/audit.c
src/util/audit.h
src/util/selinux-fallback.c
src/util/selinux.c
src/util/selinux.h

A minor rework of the audit/selinux/apparmor subsystems to avoid handling non-auditable messages and instead forwarding them to our own log.

util/audit: do not handle non-auditable messages

---

README.md
meson.build
meson_options.txt
src/clib.rs
src/lib.rs
src/meson.build
src/rlib.rs

Extend the Meson build system to compile an internal Rust library and link that into libbus.a, our internal utility library that is linked into all dbus-broker binaries.
The individual commits have extensive information on, and background for, the individual changes. To summarize, we now use the builtin Rust support of Meson to compile a static library that uses no external dependencies but standard Rust core and alloc, as well as the runtime-integration of std. This avoids the previous dance via meson-cargo, and it makes the build fully independent of Cargo.
This series merely extends the build system, but adds no meaningful Rust code. This will be added in other PRs.
(v2: rebased on the recent CI changes)

build: add infrastructure for rust (v2)

---

.github/workflows/coverity.yml
Makefile

This series provides coverity-helpers in `./Makefile` which allows to locally build and run the coverity tools. Additionally, a workflow is provided to regularly (and on demand) run coverity on `main`.
@mrc0mmand, @evverx, let me know what you think.

ci: run coverity analysis regularly

---

meson.build
src/lib-crate.rs
src/lib-generated.rs
src/lib-static.rs
src/meson.build
src/session/main.c
src/session/main.h
src/session/mod.rs
src/util/mod.rs
subprojects/libc-rs-0.2.wrap
subprojects/packagefiles/libc-rs/0001-clippy-allow-all.patch
subprojects/packagefiles/libc-rs/meson-detect-version.sh
subprojects/packagefiles/libc-rs/meson.build
subprojects/sys-1.wrap

This is an implementation of `dbus-broker-session`, imitating `dbus-run-session`. This series integrates Rust code into dbus-broker. It uses `meson-cargo` to support proper integration of Cargo-based Rust code into the Meson build system, including meson-dist support.
This is only a preview. We likely want to add `--scope=session` to `dbus-broker-launch` to prevent systemd-activation from being performed for external sessions. And we likely want to set ´DBUS_SESSION_BUS_ADDRESS` in transient units, rather than relying on the user-session to set it (which would be the wrong address).
Session buses are still rather fragile since systemd decided to enforce one bus per user, rather than one per session. Anyway, we can still make it work for most development use-cases.
Cc: @teg

session: implement dbus-broker-session
