bus1/dbus-broker

src/activation.c
src/broker/controller.c

activation: flush activation before freeing it

---

meson.build

Signed-off-by: Laurent Bigonville <bigon@bigon.be>

build: Fix libaudit detection

---

src/launch/main.c

This implements the extended search-paths for D-Bus service files.

launch: implement extended service search-paths

---

src/launch/main.c

Follow dbus-dameon(1) and only consider the first file found, ignoring all subsequent
ones. This should really be considered a configuration error, and we print a warning
in case this happens.
This addresses issue #38.

launch/service: ignore duplicate service files for the same name

---

src/bus/driver.c

Make sure we never activate services if NO_AUTO_START was specified.
While at it, align our error-codes with the codes dbus-daemon returns.

Honor NO_AUTO_START

---

README
docs/meson.build
meson.build
packaging/dbus-broker-git.spec
packaging/dbus-broker.spec

This was done manually in the specfile, let meson do it.
This addresses issue #48.

build: generate manpages

---

src/launch/main.c

This allows forked-off children to survive their parents in case the
bus-activated parent is shut down before one of their children. Moreover,
make sure to give each transient unit file a unique name, so that a
new instance can be started, even if children of an old one are still
alive.
This addresses issue #11 and #73, implementing a suggestion given in
the latter.
Reported-by: Marc-Antoine Perennou <Marc-Antoine@Perennou.com>
Reported-by: Jan Alexander Steffens<jan.steffens@gmail.com>

launcher/transient-units: use KillMode=process

---

src/broker/controller.c
src/bus/driver.c
src/bus/match.c
src/bus/name.c
src/bus/peer.c
src/bus/policy.c
src/bus/reply.c
src/launch/main.c
src/launch/policy.c
src/launch/policy.h
src/util/selinux.c
src/util/user.c

Move to the new APIs and pull in the current c-rbtree HEAD into subprojects

c-rbtree API update

---

src/launch/main.c

dbus-broker is now in the critical path during boot, it orders before
basic.target, and as such should not block unneccessarily.
The reason for delaying at all is to make sure all blocking calls from
the launcher have finished before anything else blocks on the broker.
Move the config parsing (which does the blocking calls as part of nss)
early and immediately notify PID1 of being started as soon as that is
done.
On my machine this roughly halves the time dbus-broker blocks boot from
~60ms to ~30ms.

launcher: reduce time spent in STARTING state

---

src/bus/bus.h
src/bus/driver.c
src/bus/match.c
src/bus/match.h
src/bus/peer.c
src/bus/peer.h
src/bus/test-match.c
src/dbus/message.c
src/dbus/message.h
src/launch/main.c

A handful of minor fixes to not do unnecessary work.

Micro optimizations

---

src/bus/policy.c
src/launch/main.c
src/launch/policy.c
src/launch/policy.h
test/dbus/util-broker.c

This is WIP, and so far only the changes to the controller API has been implemented.

launch: support supplementing the at_console users at compile time

---

.gitmodules
src/broker/controller-dbus.c
src/bus/driver.c
src/bus/match.c
src/bus/match.h
src/bus/peer.c
src/bus/test-match.c
src/dbus/message.c
src/dbus/protocol.c
src/dbus/protocol.h

Hook up missing validation. In particular of match strings and message header fields.

Validation

---

src/bus/driver.c
src/bus/peer.c
src/bus/peer.h

Two more TODO items were left in the bus code. See the two commits for details.

bus: resolve remaining TODO items

---

src/bus/match.c
src/bus/match.h
src/bus/peer.c

Treat the inability to receive solicited directed signals as fatal, and disconnect the receiving peer.

Solicited directed signals

---

src/bus/peer.c

Two minor patches that fix a bug, and rework the check for solicited messages.

peer: rework solicited check

---

src/launch/nss-cache.c
src/units/system/dbus-broker.service.in

See the commit messages for details.

Fix deadlock with nss-systemd

---

docs/dbus-broker.rst
src/broker/main.c

This contains man-page updates for dbus-broker(1), as well as minor fixes that showed up while writing the man-page.

Doc updates and minor fixes

---

src/util/selinux.c

As it turns out, you must not call avc_destroy() if you never called
avc_open(). However, we always want to allow calling destructors at any
time and as often as you want. Hence, lets work around this and protect
the SELinux-global-variable with our own boolean state.
This fixes an issue in case dbus-broker exits early before entering the
main-loop. We would not have initialized selinux, yet, but might end up
in the destruction callback.

util/selinux: protect avc_destroy()

---

src/launch/main.c
src/meson.build
src/util/audit-fallback.c
src/util/misc.c
src/util/misc.h

We already spawn the broker with reduced privileges, drop the privileges in the launcher too.

drop privileges in launcher

---

src/bus/driver.c
src/dbus/message.c

Make sure monitoring works again after the broadcast rework.

Fix monitoring

---

src/launch/main.c

The current logic was not correctly unquoating strings, as shown
by issue #144.
To quote the dbus sources, for the code that parses Exec
```
The results are defined to be the same as those you would get from
a UNIX98 /bin/sh, as long as the input contains none of the
unsupported shell expansions. If the input does contain such
expansions, they are passed through literally.
```
The same semantics is provided by a glib helper function, so we can
simply use that.

launch: properly unescape the Exec directive from .service files

---

src/units/system/dbus-broker.service.in
src/units/user/dbus-broker.service.in

Two minor adjustments to the dbus-broker unit files. See the commit-messages for details.

Adjust unit files

---

src/launch/main.c
test/dbus/util-broker.c

Signed-off-by: Khem Raj <raj.khem@gmail.com>

Include sys/wait.h for WEXITED definition

---

src/bus/driver.c
test/dbus/test-driver.c

This also applies to unknown interfaces/methods, which was not the case before.
Add unit tests to verify the behavior.

driver: correctly return AccessDenied when calling methods before Hello

---

src/broker/main.c
src/launch/config.c
src/launch/config.h
src/launch/main.c
src/meson.build
src/util/misc.c
src/util/misc.h
src/util/string.c
src/util/string.h

It is the distro/admin's responsibility to ensure that these are reasonable.

use the configured resource limits

---

src/util/test-user.c
src/util/user.c

When calculating quotas, make sure we never run into integer overflows.
Instead, verify every calculation in a compiler builtin that catches
integer overflows.
This also adds more tests that trigger integer overflows and thus
verify we catch them correctly.
Lastly, this documents the algorithm we use, and also explains why we
use an alternative computation, which we deem faster to calculate.

util/user: fix integer overflow

---

src/broker/broker.c

This is a rebase of the old metrics PR on top of master.

bus: log bus-wide metrics on exit

---

src/bus/match.c

(CC: @benzea @teg #245)
We did not correctly flush monitor matches on peer disconnect, but only the normal subscription objects. Fix this and properly flush all matches in a registry on disconnect.
See the commit message for background information.
I have not tested this, yet. But I think this is quite likely the bug @benzea saw. Will report back when I tested it.

bus/match: flush monitor matches on disconnect

---

src/broker/main.c

We never need any ambient capabilities in the broker process, since we
never spawn further processes. However, as we are forked off from a
non-privileged launcher, we will have a non-empty ambient set. Make sure
to clear it, to avoid leaking those capabilities into sub-processes of
a possible attacker.
Note that we only ever need CAP_AUDIT_WRITE, and we should never see any
other capability. So this is only about dropping CAP_AUDIT_WRITE from a
spawned sub-processes during a possible attack.

broker/main: drop ambient capabilities

---

src/launch/launcher.c

Signed-off-by: Marcus Sundberg <marcus.sundberg@aptilo.com>

Add missing log_append_here() when logging "Ready"

---

src/util/test-sockopt.c

Newer kernels now properly return stale pidfds from AF_UNIX sockets, rather than refusing the operation. Ensure that our tests adopt to this and properly verify staleness.

test/sockopt: loosen verification of stale pidfds
